services:
  backend:
    build: ./srv
    container_name: Server
    ports:
      - "5679:5679" 
    environment:
      - PORT=5679

  frontend:
    build: ./website
    container_name: website
    ports:
      - "80:80"
    environment:
      - PORT=80
    depends_on:
      - backend
